import { NextResponse } from 'next/server';
import { v4 as uuid } from 'uuid';
import { geminiGenerate } from '@/lib/gemini';

export const runtime = 'nodejs';
export const maxDuration = 60;
export const dynamic = 'force-dynamic';

// -------- Memory engine prompt --------
const MEMORY_SYSTEM_PROMPT = `You are the AI Memory Engine — a precise context-extraction system for software and product projects.

You are NOT a summarizer. Your job is to read a raw conversation between a human and an AI assistant, then reconstruct the full working STATE of the project so that a DIFFERENT AI system can continue the work seamlessly without any prior context.

Extract concrete, specific, technical facts. Prefer exact names (files, functions, libraries, endpoints, models, versions) over vague descriptions. Never invent facts that are not supported by the transcript; if something is unknown, leave the field empty or note it in open_questions.

Respond with a SINGLE valid JSON object and NOTHING else — no markdown fences, no commentary. Use this exact schema:

{
  "project_title": string,
  "one_liner": string,
  "project_goal": string,
  "current_state": string,
  "tech_stack": string[],
  "completed_work": string[],
  "pending_work": string[],
  "architecture_decisions": string[],
  "constraints": string[],
  "key_components": string[],
  "open_questions": string[],
  "next_tasks": string[],
  "handoff_prompt": string
}

Every array item must be a concise, standalone bullet (no numbering). Keep the handoff_prompt focused and actionable, written in second person to the target AI.`;

function parseJson(raw) {
  let text = String(raw || '').trim();
  text = text.replace(/^```(json)?/i, '').replace(/```$/i, '').trim();
  try { return JSON.parse(text); } catch (e) {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start !== -1 && end > start) return JSON.parse(text.slice(start, end + 1));
    throw e;
  }
}

function asList(v) {
  if (Array.isArray(v)) return v.map((x) => String(x).trim()).filter(Boolean);
  if (typeof v === 'string' && v.trim()) return [v.trim()];
  return [];
}

function renderMarkdown(title, req, s) {
  const bullets = (items) => (items && items.length ? items.map((i) => `- ${i}`).join('\n') : '_None captured._');
  return `# 🧠 AI Memory Package — ${title}

> Generated by AI Memory · Source: ${req.source_ai} → Target: ${req.target_ai}

**${s.one_liner}**

## Handoff Prompt (paste this first)
${s.handoff_prompt}

## Project Goal
${s.project_goal}

## Current State
${s.current_state}

## Tech Stack
${bullets(s.tech_stack)}

## Completed Work
${bullets(s.completed_work)}

## Pending Work
${bullets(s.pending_work)}

## Architecture Decisions
${bullets(s.architecture_decisions)}

## Constraints
${bullets(s.constraints)}

## Key Components
${bullets(s.key_components)}

## Open Questions
${bullets(s.open_questions)}

## Next Tasks
${bullets(s.next_tasks)}
`;
}

function json(data, status = 200) { return NextResponse.json(data, { status }); }

// -------- Router --------
async function handle(req, params) {
  const path = (params?.path || []).join('/');
  const method = req.method;

  // Health
  if (!path || path === '/' || path === 'health') {
    return json({ ok: true, service: 'AI Memory', model: process.env.GEMINI_MODEL || 'gemini-2.5-flash' });
  }

  // ----- POST /memory/generate -----
  if ((path === 'memory/generate' || path === 'generate') && method === 'POST') {
    const body = await req.json().catch(() => ({}));
    const transcript = String(body?.transcript || '').trim();
    if (!transcript) return json({ detail: 'Transcript is empty' }, 400);
    if (transcript.length < 40) return json({ detail: 'Transcript is too short to build a useful memory package' }, 400);

    const sourceAi = body?.source_ai || 'Claude';
    const targetAi = body?.target_ai || 'ChatGPT';
    const titleHint = body?.project_title
      ? `\nThe user suggests the project title: "${body.project_title}".`
      : '';

    const userPrompt = `SOURCE AI (where this conversation happened): ${sourceAi}\nTARGET AI (who will receive the memory package): ${targetAi}\n${titleHint}\n\nTailor the handoff_prompt so it reads naturally when pasted into ${targetAi}.\n\n=== BEGIN CONVERSATION TRANSCRIPT ===\n${transcript}\n=== END CONVERSATION TRANSCRIPT ===`;

    let raw;
    try {
      raw = await geminiGenerate({
        systemPrompt: MEMORY_SYSTEM_PROMPT,
        userPrompt,
        temperature: 0.4,
      });
    } catch (e) {
      console.error('Gemini error:', e);
      return json({ detail: `Memory engine failed: ${e.message}` }, 502);
    }

    let parsed;
    try { parsed = parseJson(raw); }
    catch (e) {
      console.error('Parse failure. Raw Gemini response (first 500 chars):', raw?.slice?.(0, 500));
      return json({
        detail: 'Memory engine returned an unparseable response. Please try again with a shorter transcript.',
        raw_preview: raw?.slice?.(0, 400) || null,
      }, 502);
    }

    const sections = {
      one_liner: String(parsed.one_liner || '').trim(),
      project_goal: String(parsed.project_goal || '').trim(),
      current_state: String(parsed.current_state || '').trim(),
      tech_stack: asList(parsed.tech_stack),
      completed_work: asList(parsed.completed_work),
      pending_work: asList(parsed.pending_work),
      architecture_decisions: asList(parsed.architecture_decisions),
      constraints: asList(parsed.constraints),
      key_components: asList(parsed.key_components),
      open_questions: asList(parsed.open_questions),
      next_tasks: asList(parsed.next_tasks),
      handoff_prompt: String(parsed.handoff_prompt || '').trim(),
    };

    const title = (body?.project_title || parsed.project_title || 'Untitled Project').trim() || 'Untitled Project';
    const markdown = renderMarkdown(title, { source_ai: sourceAi, target_ai: targetAi }, sections);

    return json({
      id: uuid(),
      project_title: title,
      source_ai: sourceAi,
      target_ai: targetAi,
      package: sections,
      markdown,
      created_at: new Date().toISOString(),
    });
  }

  return json({ detail: 'Not Found', path }, 404);
}

export async function GET(req, ctx) {
  try { return await handle(req, await ctx.params); }
  catch (e) { console.error('API error', e); return json({ detail: e.message || 'Internal error' }, 500); }
}
export async function POST(req, ctx) {
  try { return await handle(req, await ctx.params); }
  catch (e) { console.error('API error', e); return json({ detail: e.message || 'Internal error' }, 500); }
}
